apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openvpn
spec:
  # revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        openvpn: "$CN"
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - name: openvpn
        image: $REMOTE_TAG
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
