apiVersion: v1
kind: Service
metadata:
  labels:
    openvpn: "$HOSTNAME"
  name: openvpn
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
  - port: 1194
    protocol: TCP
    targetPort: 1194
  selector:
    openvpn: "$HOSTNAME"
