apiVersion: v1
kind: Service
metadata:
  labels:
    openvpn: "$CN"
  name: openvpn
spec:
  # type: LoadBalancer
  # loadBalancerIP: $LOADBALANCER_IP
  ports:
  - port: 1194
    protocol: TCP
    targetPort: 1194
  selector:
    openvpn: "$CN"
