apiVersion: v1
kind: Service
metadata:
  name: openvpn
  labels:
    app: openvpn
spec:
  type: LoadBalancer
  selector:
    app: openvpn
  ports:
    - name: tcp
      port: 1194
      protocol: TCP
      targetPort: 1194

