apiVersion: v1
kind: Service
metadata:
  labels:
    openvpn: "$CN"
  name: openvpn
spec:
  # type: LoadBalancer
  # loadBalancerIP: $LOADBALANCER_IP
  ports:
  - name: tcp
    port: 1194
    protocol: TCP
    targetPort: 1194
  - name: udp
    port: 1194
    protocol: UDP
    targetPort: 1194
  selector:
    openvpn: "$CN"
